package com.monitorecg.hibernate.entities;
// Generated 16-mar-2016 13:26:37 by Hibernate Tools 4.3.1



/**
 * PacienteId generated by hbm2java
 */
public class PacienteId  implements java.io.Serializable {


     private int idPaciente;
     private int cardiologoIdCardiologo;

    public PacienteId() {
    }

    public PacienteId(int idPaciente, int cardiologoIdCardiologo) {
       this.idPaciente = idPaciente;
       this.cardiologoIdCardiologo = cardiologoIdCardiologo;
    }
   
    public int getIdPaciente() {
        return this.idPaciente;
    }
    
    public void setIdPaciente(int idPaciente) {
        this.idPaciente = idPaciente;
    }
    public int getCardiologoIdCardiologo() {
        return this.cardiologoIdCardiologo;
    }
    
    public void setCardiologoIdCardiologo(int cardiologoIdCardiologo) {
        this.cardiologoIdCardiologo = cardiologoIdCardiologo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PacienteId) ) return false;
		 PacienteId castOther = ( PacienteId ) other; 
         
		 return (this.getIdPaciente()==castOther.getIdPaciente())
 && (this.getCardiologoIdCardiologo()==castOther.getCardiologoIdCardiologo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdPaciente();
         result = 37 * result + this.getCardiologoIdCardiologo();
         return result;
   }   


}


